### PR TITLE
Adding a repo template

### PR DESCRIPTION
**Pull request by RichardLitt**
@dxnn I think this is a pretty good template. I actually like having the reasoning above - it helps people approach and understand the list in a certain light. What do you think?

### CODE REVIEW

**Comment by dxnn** [comment]
Looks good! I agree that having some explanatory text at the top is helpful in giving context and purpose. I like that the content is explicitly CC licensed, though I wonder if we can move that licensing into a separate license file in the repo, so that we can open up the footer to reflect the names of all the maintainers of that city's repo, rather than just the one who started it. That also gives us a chance to be explicit about who is responsible and who to contact if there are any issues. What do you think?

**Comment by RichardLitt** [comment]
> though I wonder if we can move that licensing into a separate license file in the repo

Yes, that is where the full text should be. The README should grow to reflect contributors. However, this should be on a per-contributor basis; anyone who wishes to add themselves can, but most contributors just want a PR and to leave it at that. I think that having the initial owner have the license is not a problem, and saves some headache down the road. 

A `Maintainers` section would be good to know who to contact, too. I can add this? This is normally different from the licensee.

**Comment by RichardLitt** [comment]
Take a look at the proposed maintainers section.

**Comment by dxnn** [comment]
Looks good! I'm hoping to promote the Toronto repo a bit at an event this weekend, so I'm going to merge this PR and get to work on migrating the changes over to that repo. I'll make a new PR to the template if I discover any issues while doing that.

**Pull request merged**
